#!/usr/bin/env bash
# =============================================================================
# setup-server.sh – Render wg0.conf from keys + .env and start the server.
#
# Usage (run from the repo root):
#   cp .env.example .env && nano .env
#   ./scripts/setup-server.sh
#
# What it does:
#   1. Validates dependencies and .env
#   2. Generates key material (calls generate-keys.sh if keys are missing)
#   3. Renders server/wg0.conf from the template
#   4. Starts (or restarts) the Docker Compose stack
# =============================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
KEYS_DIR="$REPO_ROOT/keys"
ENV_FILE="$REPO_ROOT/.env"
SERVER_DIR="$REPO_ROOT/server"

# ---------- helpers -----------------------------------------------------------
die()  { echo "ERROR: $*" >&2; exit 1; }
info() { echo "  --> $*"; }

require_cmd() { command -v "$1" >/dev/null 2>&1 || die "'$1' not found. $2"; }

# ---------- pre-flight checks -------------------------------------------------
require_cmd docker    "Install Docker: https://docs.docker.com/get-docker/"
require_cmd wg        "Install wireguard-tools (apt/yum/brew install wireguard-tools)"

[[ -f "$ENV_FILE" ]] || die ".env not found. Run: cp .env.example .env && nano .env"

# shellcheck source=/dev/null
source "$ENV_FILE"

[[ -n "${WG_HOST:-}" ]]          || die "WG_HOST is not set in .env"
[[ "${WG_HOST}" != "your.server.public.ip.or.domain" ]] || \
  die "WG_HOST is still the placeholder value. Set it to your server's public IP or FQDN."

# ---------- generate keys (idempotent) ----------------------------------------
info "Generating keys (skipped if already present)…"
bash "$REPO_ROOT/scripts/generate-keys.sh" "$KEYS_DIR"

# ---------- load keys into variables ------------------------------------------
read_key() { cat "$KEYS_DIR/$1"; }

SERVER_PRIVKEY=$(read_key server.privkey)
SITE_A_PUBKEY=$(read_key site-a.pubkey)
SITE_A_PSK=$(read_key preshared-site-a.key)
SITE_B_PUBKEY=$(read_key site-b.pubkey)
SITE_B_PSK=$(read_key preshared-site-b.key)
RW_PUBKEY=$(read_key road-warrior.pubkey)
RW_PSK=$(read_key preshared-road-warrior.key)

SITE_A_LAN="${SITE_A_LAN:-192.168.1.0/24}"
SITE_B_LAN="${SITE_B_LAN:-192.168.2.0/24}"
SITE_A_VPN_IP="${SITE_A_VPN_IP:-10.8.0.2}"
SITE_B_VPN_IP="${SITE_B_VPN_IP:-10.8.0.3}"
ROAD_WARRIOR_START_IP="${ROAD_WARRIOR_START_IP:-10.8.0.10}"
WG_PORT="${WG_PORT:-51820}"

# ---------- render wg0.conf ---------------------------------------------------
mkdir -p "$SERVER_DIR"
info "Rendering server/wg0.conf…"

cat > "$SERVER_DIR/wg0.conf" <<EOF
# WireGuard server configuration – generated by setup-server.sh
# DO NOT commit this file; it contains private key material.

[Interface]
Address    = 10.8.0.1/24
ListenPort = ${WG_PORT}
PrivateKey = ${SERVER_PRIVKEY}
# Enable IP forwarding and masquerade for road-warrior internet access
PostUp     = sysctl -w net.ipv4.ip_forward=1; \\
             iptables -A FORWARD -i %i -j ACCEPT; \\
             iptables -A FORWARD -o %i -j ACCEPT; \\
             iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown   = iptables -D FORWARD -i %i -j ACCEPT; \\
             iptables -D FORWARD -o %i -j ACCEPT; \\
             iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

# ---- Site-A (main home network: ${SITE_A_LAN}) -----
[Peer]
PublicKey           = ${SITE_A_PUBKEY}
PresharedKey        = ${SITE_A_PSK}
AllowedIPs          = ${SITE_A_VPN_IP}/32, ${SITE_A_LAN}
PersistentKeepalive = 25

# ---- Site-B (secondary network: ${SITE_B_LAN}) -----
[Peer]
PublicKey           = ${SITE_B_PUBKEY}
PresharedKey        = ${SITE_B_PSK}
AllowedIPs          = ${SITE_B_VPN_IP}/32, ${SITE_B_LAN}
PersistentKeepalive = 25

# ---- Road-warrior (full-tunnel, streaming) ---------
[Peer]
PublicKey           = ${RW_PUBKEY}
PresharedKey        = ${RW_PSK}
AllowedIPs          = ${ROAD_WARRIOR_START_IP}/32
PersistentKeepalive = 25
EOF

chmod 600 "$SERVER_DIR/wg0.conf"
info "Server config written to $SERVER_DIR/wg0.conf"

# ---------- start the stack ---------------------------------------------------
info "Starting Docker Compose stack…"
cd "$REPO_ROOT"
docker compose up -d --pull always

info "Done! WireGuard server is running."
info "Web UI available at http://127.0.0.1:51821 (use an SSH tunnel or reverse-proxy for remote access)"
info ""
info "Next steps:"
info "  1. Configure the Site-A gateway: ./scripts/setup-client.sh site-a"
info "  2. Configure the Site-B gateway: ./scripts/setup-client.sh site-b"
info "  3. Configure a road-warrior:     ./scripts/setup-client.sh road-warrior"
